### ISSUE TITLE
Failed stage_files.py on Summit

### ISSUE THREAD

**Issue by mrnorman** [RobertPincus/rte-rrtmgp#49]
On Summit, we get the following failure with `stage_files.py` using the following from a fresh conda install:

```
module load python/3.7.0-anaconda3-5.3.0
conda create -n newenv python=3.7 anaconda
source activate newenv
conda install netcdf4 xarray numpy
python ./stage_files.py
```
Conda env here: https://gist.github.com/mrnorman/be751789d5357b45453d56c8a4c917db

```bash
(newenv) [imn@login2:~/rte-rrtmgp/examples/rfmip-clear-sky] 8-) python ./stage_files.py 
Dowloading RFMIP input files
Dowloading scripts for generating output templates
Traceback (most recent call last):
  File "./stage_files.py", line 34, in <module>
    urllib.request.urlretrieve(templ_scr_url, templ_scr)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/urllib/request.py", line 1285, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/http/client.py", line 1368, in __init__
    context = ssl._create_default_https_context()
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/ssl.py", line 565, in create_default_context
    context = SSLContext(PROTOCOL_TLS)
  File "/ccs/home/imn/.conda/envs/newenv/lib/python3.7/ssl.py", line 388, in __new__
    self = _SSLContext.__new__(cls, protocol)
ssl.SSLError: [SSL] malloc failure (_ssl.c:2994)
(newenv) [imn@login2:~/rte-rrtmgp/examples/rfmip-clear-sky] >:O 
```

**Comment by brhillman** [comment]
I was able to recreate this, and then solve it by downgrading to openssl=1.1.1b.

**Comment by brhillman** [comment]
Easier way to create the environment:
```
conda create -n rrtmgp-env python=3.7 openssl=1.1.1b numpy netcdf4 xarray
source activate rrtmgp-env
```

**Comment by RobertPincus** [comment]
@brhillman @mrnorman Can either of you parse the errors and tell me what they mean? It's a simple request for a file.

**Comment by brhillman** [comment]
@RobertPincus "tell you what they mean" I don't know about that, it doesn't really make sense to me, but downgrading to an older version of openssl solved it for me, so I suspect it's a problem with the SSL library not something in the script.

**Comment by RobertPincus** [comment]
@brhillman @mrnorman Do we leave the issue open? How would we resolve this?

**Comment by brhillman** [comment]
@RobertPincus I'm okay to close this, since I don't think it's a problem with the script itself.

**Comment by mrnorman** [comment]
Totally fine with me. I just wanted to document it

**Comment by RobertPincus** [comment]
Thanks for figuring out what was wrong, anyway.
